In [112]:
import pandas as pd
import plotly.express as px

In [87]:
df = pd.read_csv("data/apps.csv")
df

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
0,Ak Parti Yardım Toplama,SOCIAL,NaN,0,8.7,0,Paid,$13.99,Teen,Social,"July 28, 2017",4.1 and up
1,Ain Arabic Kids Alif Ba ta,FAMILY,NaN,0,33.0,0,Paid,$2.99,Everyone,Education,"April 15, 2016",3.0 and up
2,Popsicle Launcher for Android P 9.0 launcher,PERSONALIZATION,NaN,0,5.5,0,Paid,$1.49,Everyone,Personalization,"July 11, 2018",4.2 and up
3,Command & Conquer: Rivals,FAMILY,NaN,0,19.0,0,NaN,0,Everyone 10+,Strategy,"June 28, 2018",Varies with device
4,CX Network,BUSINESS,NaN,0,10.0,0,Free,0,Everyone,Business,"August 6, 2018",4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Subway Surfers,GAME,4.5,27723193,76.0,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up
10837,Subway Surfers,GAME,4.5,27724094,76.0,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up
10838,Subway Surfers,GAME,4.5,27725352,76.0,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up
10839,Subway Surfers,GAME,4.5,27725352,76.0,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up
10840,Subway Surfers,GAME,4.5,27711703,76.0,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up

In [88]:
df.sample(10)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
1734,Pin-fo,FAMILY,4.6,19,1.60,500,Free,0,Everyone,Entertainment,"August 15, 2016",2.2 and up
1304,CF Etowah,HEALTH_AND_FITNESS,NaN,0,8.80,100,Free,0,Everyone,Health & Fitness,"July 9, 2018",4.1 and up
6789,Babbel – Learn Spanish,EDUCATION,4.4,54798,11.00,"1,000,000",Free,0,Everyone,Education,"July 30, 2018",4.4 and up
4533,AJ Jump: Animal Jam Kangaroos!,GAME,4.4,2975,42.00,"50,000",Paid,$1.99,Everyone,Arcade,"March 7, 2016",4.0 and up
3140,Christella VoiceUp,MEDICAL,4.1,38,70.00,"5,000",Free,0,Everyone,Medical,"July 12, 2018",4.1 and up
7919,Offroad 4x4 Car Driving,FAMILY,4.3,26224,43.00,"1,000,000",Free,0,Everyone,Simulation,"April 29, 2017",2.3 and up
6974,"Freeform – Stream Full Episodes, Movies, & Liv...",FAMILY,3.7,29229,19.00,"1,000,000",Free,0,Teen,Entertainment,"August 6, 2018",Varies with device
6055,At home - rental · real estate · room finding ...,HOUSE_AND_HOME,3.8,2496,8.85,"500,000",Free,0,Everyone,House & Home,"July 5, 2018",Varies with device
6183,search.ch,TRAVEL_AND_LOCAL,4.4,11514,2.20,"500,000",Free,0,Everyone,Travel & Local,"March 29, 2018",4.0 and up
7916,I LOVE PASTA,FAMILY,4.0,83875,43.00,"1,000,000",Free,0,Everyone,Simulation,"September 8, 2017",2.3.3 and up

In [89]:
df.shape

(10841, 12)

In [90]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size_MBs', 'Installs', 'Type',
       'Price', 'Content_Rating', 'Genres', 'Last_Updated', 'Android_Ver'],
      dtype='str')

In [91]:
df.dtypes

App                   str
Category              str
Rating            float64
Reviews             int64
Size_MBs          float64
Installs              str
Type                  str
Price                 str
Content_Rating        str
Genres                str
Last_Updated          str
Android_Ver           str
dtype: object

In [92]:
# remove unnecessary columns
df = df.drop(columns=["Last_Updated","Android_Ver"])
df.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
0,Ak Parti Yardım Toplama,SOCIAL,NaN,0,8.7,0,Paid,$13.99,Teen,Social
1,Ain Arabic Kids Alif Ba ta,FAMILY,NaN,0,33.0,0,Paid,$2.99,Everyone,Education
2,Popsicle Launcher for Android P 9.0 launcher,PERSONALIZATION,NaN,0,5.5,0,Paid,$1.49,Everyone,Personalization
3,Command & Conquer: Rivals,FAMILY,NaN,0,19.0,0,NaN,0,Everyone 10+,Strategy
4,CX Network,BUSINESS,NaN,0,10.0,0,Free,0,Everyone,Business

In [93]:
df.shape

(10841, 10)

In [94]:
nan_rows = df[df.Rating.isna()]
print(nan_rows.shape)

(1474, 10)

In [95]:
# remove NaN based on the  rating column
df_apps_clean = df.dropna(subset=['Rating'])
df_apps_clean.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.0,4,25.0,1,Free,0,Everyone,Medical
28,Ra Ga Ba,GAME,5.0,2,20.0,1,Paid,$1.49,Everyone,Arcade
47,Mu.F.O.,GAME,5.0,2,16.0,1,Paid,$0.99,Everyone,Arcade
82,Brick Breaker BR,GAME,5.0,7,19.0,5,Free,0,Everyone,Arcade
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.0,1,4.6,5,Free,0,Everyone,Medical

In [96]:
# identify duplicates and remove them
duplicated_rows = df_apps_clean[df_apps_clean.duplicated()]
print(duplicated_rows.shape)
duplicated_rows.head()

(476, 10)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
946,420 BZ Budeze Delivery,MEDICAL,5.0,2,11.0,100,Free,0,Mature 17+,Medical
1133,MouseMingle,DATING,2.7,3,3.9,100,Free,0,Mature 17+,Dating
1196,"Cardiac diagnosis (heart rate, arrhythmia)",MEDICAL,4.4,8,6.5,100,Paid,$12.99,Everyone,Medical
1231,Sway Medical,MEDICAL,5.0,3,22.0,100,Free,0,Everyone,Medical
1247,Chat Kids - Chat Room For Kids,DATING,4.7,6,4.9,100,Free,0,Mature 17+,Dating

In [97]:
df_apps_clean[df_apps_clean.App=='Instagram']

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10806,Instagram,SOCIAL,4.5,66577313,5.3,"1,000,000,000",Free,0,Teen,Social
10808,Instagram,SOCIAL,4.5,66577446,5.3,"1,000,000,000",Free,0,Teen,Social
10809,Instagram,SOCIAL,4.5,66577313,5.3,"1,000,000,000",Free,0,Teen,Social
10810,Instagram,SOCIAL,4.5,66509917,5.3,"1,000,000,000",Free,0,Teen,Social

In [98]:
df_apps_clean=df_apps_clean.drop_duplicates(subset=['App','Type','Price'])

In [99]:
df_apps_clean.shape

(8199, 10)

In [100]:
# apps highly rated
highly_rated_apps = df_apps_clean.loc[df_apps_clean.Rating.idxmax()]
highly_rated_apps

App               KBA-EZ Health Guide
Category                      MEDICAL
Rating                            5.0
Reviews                             4
Size_MBs                         25.0
Installs                            1
Type                             Free
Price                               0
Content_Rating               Everyone
Genres                        Medical
Name: 21, dtype: object

In [101]:
# apps with highest reviews
reviewed_high_apps = df_apps_clean.sort_values(by=["Reviews"],ascending=False)
reviewed_high_apps

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10805,Facebook,SOCIAL,4.1,78158306,5.3,"1,000,000,000",Free,0,Teen,Social
10785,WhatsApp Messenger,COMMUNICATION,4.4,69119316,3.5,"1,000,000,000",Free,0,Everyone,Communication
10806,Instagram,SOCIAL,4.5,66577313,5.3,"1,000,000,000",Free,0,Teen,Social
10784,Messenger – Text and Video Chat for Free,COMMUNICATION,4.0,56642847,3.5,"1,000,000,000",Free,0,Everyone,Communication
10650,Clash of Clans,GAME,4.6,44891723,98.0,"100,000,000",Free,0,Everyone 10+,Strategy
...,...,...,...,...,...,...,...,...,...,...
728,Truck Driving Test Class 3 BC,FAMILY,1.0,1,2.0,50,Paid,$1.49,Everyone,Education
485,Familyfirst Messenger,MEDICAL,4.0,1,3.3,10,Free,0,Everyone,Medical
617,DT future1 cam,TOOLS,1.0,1,24.0,50,Free,0,Everyone,Tools
496,CI 174 Gray Icon Pack,PERSONALIZATION,5.0,1,46.0,10,Paid,$0.99,Everyone,Personalization
151,EB Cash Collections,BUSINESS,5.0,1,4.3,5,Free,0,Everyone,Business

In [102]:
rated_high_apps = df_apps_clean.sort_values(by=["Rating"],ascending=False)
rated_high_apps

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.0,4,25.0,1,Free,0,Everyone,Medical
1751,Spine- The dating app,DATING,5.0,5,9.3,500,Free,0,Teen,Dating
1761,Selfie With Champion AJ Style,PHOTOGRAPHY,5.0,2,7.5,500,Free,0,Everyone,Photography
1763,Ag Valley Cooperative,BUSINESS,5.0,6,74.0,500,Free,0,Everyone,Business
1769,Yazdani Cd Center EllahAbad Official App,FAMILY,5.0,8,3.8,500,Free,0,Everyone,Entertainment
...,...,...,...,...,...,...,...,...,...,...
818,Familial Hypercholesterolaemia Handbook,MEDICAL,1.0,2,33.0,100,Free,0,Everyone,Medical
1208,Thistletown CI,PRODUCTIVITY,1.0,1,6.6,100,Free,0,Everyone,Productivity
1314,CR Magazine,BUSINESS,1.0,1,7.8,100,Free,0,Everyone,Business
1679,CB Mobile Biz,FINANCE,1.0,3,8.4,500,Free,0,Everyone,Finance
1721,Lottery Ticket Checker - Florida Results & Lotto,TOOLS,1.0,3,41.0,500,Free,0,Everyone,Tools

In [103]:
# visualize using plotly
content_rating = df_apps_clean["Content_Rating"].value_counts()
content_rating

Content_Rating
Everyone           6621
Teen                912
Mature 17+          357
Everyone 10+        305
Adults only 18+       3
Unrated               1
Name: count, dtype: int64

In [104]:
# content_rating visualization using pie
fig = px.pie(labels=content_rating.index,
             values=content_rating.values,
             title="Content Rating",
             names=content_rating.index
             )
fig.update_traces(textposition='outside',textinfo='percent+label')
fig.show()

In [105]:
# content_rating visualization using donut
fig = px.pie(labels=content_rating.index,
             values=content_rating.values,
             title="Content Rating",
             names=content_rating.index,
             hole=0.6
             )
fig.update_traces(textposition='outside',textinfo='percent',textfont_size=15)
fig.show()

In [106]:
df_apps_clean.dtypes

App                   str
Category              str
Rating            float64
Reviews             int64
Size_MBs          float64
Installs              str
Type                  str
Price                 str
Content_Rating        str
Genres                str
dtype: object

In [107]:
df_apps_clean[df_apps_clean.App == "Facebook"]

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10805,Facebook,SOCIAL,4.1,78158306,5.3,"1,000,000,000",Free,0,Teen,Social

In [108]:
df_apps_clean[df_apps_clean.App == "Facebook"]["Installs"]

10805    1,000,000,000
Name: Installs, dtype: str

In [111]:
df_apps_clean[["App",'Installs']].groupby("Installs").count()

                App
Installs
1                 3
1,000           698
1,000,000      1417
1,000,000,000    20
10               69
10,000          988
10,000,000      933
100             303
100,000        1096
100,000,000     189
5                 9
5,000           425
5,000,000       607
50               56
50,000          457
50,000,000      202
500             199
500,000         504
500,000,000      24

In [113]:
df_apps_clean["Installs"]= df_apps_clean["Installs"].str.replace(',', "",regex=False).str.replace('+',"",regex=False).astype(int)

In [114]:
df_apps_clean[["App",'Installs']].groupby("Installs").count()

             App
Installs
1              3
5              9
10            69
50            56
100          303
500          199
1000         698
5000         425
10000        988
50000        457
100000      1096
500000       504
1000000     1417
5000000      607
10000000     933
50000000     202
100000000    189
500000000     24
1000000000    20

In [115]:
df_apps_clean.dtypes

App                   str
Category              str
Rating            float64
Reviews             int64
Size_MBs          float64
Installs            int64
Type                  str
Price                 str
Content_Rating        str
Genres                str
dtype: object

In [116]:
df_apps_clean.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.0,4,25.0,1,Free,0,Everyone,Medical
28,Ra Ga Ba,GAME,5.0,2,20.0,1,Paid,$1.49,Everyone,Arcade
47,Mu.F.O.,GAME,5.0,2,16.0,1,Paid,$0.99,Everyone,Arcade
82,Brick Breaker BR,GAME,5.0,7,19.0,5,Free,0,Everyone,Arcade
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.0,1,4.6,5,Free,0,Everyone,Medical

In [118]:
df_apps_clean["Price"]= df_apps_clean["Price"].str.replace(',', "",regex=False).str.replace('$',"",regex=False).astype(float)

In [119]:
df_apps_clean.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.0,4,25.0,1,Free,0.00,Everyone,Medical
28,Ra Ga Ba,GAME,5.0,2,20.0,1,Paid,1.49,Everyone,Arcade
47,Mu.F.O.,GAME,5.0,2,16.0,1,Paid,0.99,Everyone,Arcade
82,Brick Breaker BR,GAME,5.0,7,19.0,5,Free,0.00,Everyone,Arcade
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.0,1,4.6,5,Free,0.00,Everyone,Medical

In [121]:
df_apps_clean.dtypes

App                   str
Category              str
Rating            float64
Reviews             int64
Size_MBs          float64
Installs            int64
Type                  str
Price             float64
Content_Rating        str
Genres                str
dtype: object

In [122]:
df_apps_clean[df_apps_clean.App == "Facebook"]["Installs"]

10805    1000000000
Name: Installs, dtype: int64

In [124]:
df_apps_clean["Revenue_Estimate"] = df_apps_clean["Installs"] * df_apps_clean["Price"]

In [141]:
top_10_paid_apps = df_apps_clean.sort_values("Revenue_Estimate",ascending=False).head(10)
top_10_paid_apps

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Revenue_Estimate
9220,Minecraft,FAMILY,4.5,2376564,19.000000,10000000,Paid,6.99,Everyone 10+,Arcade;Action & Adventure,69900000.0
5765,I am rich,LIFESTYLE,3.8,3547,1.800000,100000,Paid,399.99,Everyone,Lifestyle,39999000.0
4606,I Am Rich Premium,FINANCE,4.1,1867,4.700000,50000,Paid,399.99,Everyone,Finance,19999500.0
8825,Hitman Sniper,GAME,4.6,408292,29.000000,10000000,Paid,0.99,Mature 17+,Action,9900000.0
7151,Grand Theft Auto: San Andreas,GAME,4.4,348962,26.000000,1000000,Paid,6.99,Mature 17+,Action,6990000.0
7477,Facetune - For Free,PHOTOGRAPHY,4.4,49553,48.000000,1000000,Paid,5.99,Everyone,Photography,5990000.0
7977,Sleep as Android Unlock,LIFESTYLE,4.5,23966,0.851562,1000000,Paid,5.99,Everyone,Lifestyle,5990000.0
6594,DraStic DS Emulator,GAME,4.6,87766,12.000000,1000000,Paid,4.99,Everyone,Action,4990000.0
3946,I'm Rich - Trump Edition,LIFESTYLE,3.6,275,7.300000,10000,Paid,400.00,Everyone,Lifestyle,4000000.0
3554,💎 I'm rich,LIFESTYLE,3.8,718,26.000000,10000,Paid,399.99,Everyone,Lifestyle,3999900.0

In [143]:
(top_10_paid_apps["Category"] == "GAME").sum()

np.int64(3)

In [145]:
top_10_paid_apps.groupby("Category").size()

Category
FAMILY         1
FINANCE        1
GAME           3
LIFESTYLE      4
PHOTOGRAPHY    1
dtype: int64

In [146]:
top_10_paid_apps.groupby('Category')['Revenue_Estimate'].sum().sort_values(ascending=False)

Category
FAMILY         69900000.0
LIFESTYLE      53988900.0
GAME           21880000.0
FINANCE        19999500.0
PHOTOGRAPHY     5990000.0
Name: Revenue_Estimate, dtype: float64

In [147]:
df_apps_clean.Category.nunique()

33

In [148]:
top_10_category = df_apps_clean.Category.value_counts()[:10]
top_10_category

Category
FAMILY             1610
GAME                910
TOOLS               719
LIFESTYLE           302
FINANCE             302
PRODUCTIVITY        301
PERSONALIZATION     298
MEDICAL             292
PHOTOGRAPHY         263
BUSINESS            262
Name: count, dtype: int64

In [149]:
bar = px.bar(x=top_10_category.index,
             y=top_10_category.values)
bar.show()

In [161]:
category_installs = df_apps_clean.groupby('Category').agg({'Installs': pd.Series.sum})
category_installs.sort_values('Installs', ascending=True, inplace=True)

In [164]:
h_bar = px.bar(x = category_installs.Installs,
               y = category_installs.index,
               orientation='h',
               title='Category Popularity')

h_bar.update_layout(xaxis_title='Number of Downloads', yaxis_title='Category')
h_bar.show()

In [168]:
category_concentration = df_apps_clean.groupby('Category').agg({'App': pd.Series.count,'Installs': pd.Series.sum})
category_concentration.sort_values("Installs",ascending=False,inplace=True)

In [169]:
scatter = px.scatter(category_concentration, # data
                    x='App', # column name
                    y='Installs',
                    title='Category Concentration',
                    size='App',
                    hover_name=category_concentration.index,
                    color='Installs')

scatter.update_layout(xaxis_title="Number of Apps (Lower=More Concentrated)",
                      yaxis_title="Installs",
                      yaxis=dict(type='log'))

scatter.show()

In [170]:
# nested columns
len(df_apps_clean.Genres.unique())

114

In [173]:
df_apps_clean.Genres.value_counts(ascending=False).head(10)

Genres
Tools              718
Entertainment      471
Education          429
Finance            302
Productivity       301
Lifestyle          301
Personalization    298
Medical            292
Action             292
Sports             266
Name: count, dtype: int64

In [176]:
stack = df_apps_clean.Genres.str.split(';', expand=True).stack()
print(f'We now have a single column with shape: {stack.shape}')
num_genres = stack.value_counts()
print(f'Number of genres: {len(num_genres)}')

We now have a single column with shape: (16398,)
Number of genres: 53

In [177]:
num_genres

Tools                      719
Education                  587
Entertainment              502
Action                     304
Lifestyle                  303
Finance                    302
Productivity               301
Personalization            298
Medical                    292
Sports                     270
Photography                263
Business                   262
Communication              258
Health & Fitness           245
Casual                     216
News & Magazines           204
Social                     203
Simulation                 200
Travel & Local             187
Arcade                     185
Shopping                   180
Books & Reference          171
Video Players & Editors    150
Dating                     134
Puzzle                     124
Maps & Navigation          118
Role Playing               111
Racing                     103
Action & Adventure          96
Strategy                    95
Food & Drink                94
Educational                 93
Adventure                   78
Auto & Vehicles             73
Weather                     72
Pretend Play                68
Brain Games                 65
Libraries & Demo            64
Art & Design                62
House & Home                62
Board                       57
Comics                      54
Parenting                   50
Card                        46
Events                      45
Beauty                      42
Casino                      37
Creativity                  31
Music & Video               31
Trivia                      28
Word                        22
Music                       21
Music & Audio                1
Name: count, dtype: int64

In [178]:
bar = px.bar(x = num_genres.index[:15], # index = category name
             y = num_genres.values[:15], # count
             title='Top Genres',
             hover_name=num_genres.index[:15],
             color=num_genres.values[:15],
             color_continuous_scale='Agsunset')

bar.update_layout(xaxis_title='Genre',yaxis_title='Number of Apps',coloraxis_showscale=False)

bar.show()

In [179]:
df_apps_clean.Type.value_counts()

Type
Free    7595
Paid     604
Name: count, dtype: int64

In [180]:
df_free_vs_paid = df_apps_clean.groupby(["Category", "Type"], as_index=False).agg({'App': pd.Series.count})
df_free_vs_paid.head()

            Category  Type  App
0     ART_AND_DESIGN  Free   58
1     ART_AND_DESIGN  Paid    3
2  AUTO_AND_VEHICLES  Free   72
3  AUTO_AND_VEHICLES  Paid    1
4             BEAUTY  Free   42

In [181]:
g_bar = px.bar(df_free_vs_paid,
               x='Category',
               y='App',
               title='Free vs Paid Apps by Category',
               color='Type',
               barmode='group')

g_bar.update_layout(xaxis_title='Category',
                    yaxis_title='Number of Apps',
                    xaxis={'categoryorder':'total descending'},
                    yaxis=dict(type='log'))

g_bar.show()